/**
 * Метки правил поставляемого CRS -- подстановка поля «Метки» у повода
 * «Сработало правило». Словарём поле не становится: локальные правила профиля
 * вешают свои метки, и они вводятся руками, буква в букву, как их показывает
 * карточка события.
 *
 * Выписано из coraza-coreruleset v4.25.0 (версия -- modsec/go.mod): все
 * `tag:'…'` набора, кроме `capec/…` -- номера каталога CAPEC ничего не говорят
 * оператору в подстановке, а в карточке события они видны целиком. Инспектор
 * сравнивает метку байт в байт, поэтому здесь слова движка, а не перевод.
 *
 * Порядок -- от меток атак к служебным. Голая `OWASP_CRS` стоит последней:
 * её несут и служебные правила с сообщением, а 901340 «Enabling body
 * inspection» срабатывает почти на каждом GET -- строка на ней дёргалась бы
 * всегда.
 */
export const CRS_TAGS: readonly string[] = [
  "attack-sqli",
  "attack-xss",
  "attack-rce",
  "attack-lfi",
  "attack-rfi",
  "attack-ssrf",
  "attack-ssti",
  "attack-injection-php",
  "attack-injection-java",
  "attack-injection-generic",
  "attack-protocol",
  "attack-multipart-header",
  "attack-fixation",
  "attack-disclosure",
  "attack-reputation-scanner",
  "attack-deprecated-header",
  "attack-generic",
  "OWASP_CRS/ATTACK-SQLI",
  "OWASP_CRS/ATTACK-XSS",
  "OWASP_CRS/ATTACK-RCE",
  "OWASP_CRS/ATTACK-LFI",
  "OWASP_CRS/ATTACK-RFI",
  "OWASP_CRS/ATTACK-PHP",
  "OWASP_CRS/ATTACK-JAVA",
  "OWASP_CRS/ATTACK-GENERIC",
  "OWASP_CRS/ATTACK-SESSION-FIXATION",
  "OWASP_CRS/PROTOCOL-ENFORCEMENT",
  "OWASP_CRS/PROTOCOL-ATTACK",
  "OWASP_CRS/MULTIPART-ATTACK",
  "OWASP_CRS/METHOD-ENFORCEMENT",
  "OWASP_CRS/SCANNER-DETECTION",
  "OWASP_CRS/WEB-SHELLS",
  "OWASP_CRS/DATA-LEAKAGES",
  "OWASP_CRS/DATA-LEAKAGES-SQL",
  "OWASP_CRS/DATA-LEAKAGES-JAVA",
  "OWASP_CRS/DATA-LEAKAGES-PHP",
  "OWASP_CRS/DATA-LEAKAGES-IIS",
  "OWASP_CRS/DATA-LEAKAGES-RUBY",
  "paranoia-level/1",
  "paranoia-level/2",
  "paranoia-level/3",
  "paranoia-level/4",
  "language-multi",
  "language-php",
  "language-java",
  "language-javascript",
  "language-shell",
  "language-powershell",
  "language-perl",
  "language-ruby",
  "language-aspnet",
  "language-ldap",
  "platform-multi",
  "platform-unix",
  "platform-windows",
  "platform-apache",
  "platform-iis",
  "platform-tomcat",
  "platform-nodejs",
  "platform-internet-explorer",
  "platform-mysql",
  "platform-mssql",
  "platform-pgsql",
  "platform-oracle",
  "platform-sqlite",
  "platform-db2",
  "platform-sybase",
  "platform-informix",
  "platform-ingres",
  "platform-interbase",
  "platform-firebird",
  "platform-frontbase",
  "platform-hsqldb",
  "platform-maxdb",
  "platform-msaccess",
  "platform-emc",
  "application-multi",
  "anomaly-evaluation",
  "header-allowlist",
  "reporting",
  "xss-perf-disable",
  "OWASP_CRS",
];
